### PR TITLE
added interface to set bias and removed bias update

### PR DESCRIPTION
**Pull request by yimingjiang**
@christos-c @danyaljj Please review this PR.

When I was using `SparseWinnow`, I ran into the problem that the accuracy is always around 50%. The issue is that `SparseWinnow` use a constant 1 as bias(theta) and there is no way to set it by the user.

For winnow update rule: y(wT dot x + theta) < margin. Initially weight vector is inited to all 1s, it's very likely (wT dot x + 1) > 0. When y is either 0 or negative, regardless of making a mistake or not, the winnow is always demoting in this case. This deviates greatly from the essence of the update rule of winnow algorithm.

It's suggested in CS 446 homework 3 handout that setting theta to -n, where n is the number of features and do not update it.

I have tested using the updated winnow algorithm, with 10 iterations producing 99.98% accuracy.

### CODE REVIEW

**Comment by danyaljj** [comment]
@penghaoruo @shyamupa @cttsai @mayhewsw have you used this classifier? What are your opinions on this PR?

**Comment by danyaljj** [comment]
FYI @mssammon @danr-ccg

**Comment by mssammon** [comment]
@yimingjiang what data sets did you test on? When you say 
"When y is either 0 or negative, regardless of making a mistake or not, the winnow is always demoting in this case."
I don't understand what you mean by "regardless of making a mistake or not" -- if the weight vector is too high, a negative label leads to demotion, and by definition the learner made a mistake, no?

**Comment by yimingjiang** [comment]
@mssammon 

I am using the data set proposed in CS 446 Homework 3(https://www.dropbox.com/s/o3oo88yyk33en4f/hw3.pdf?dl=0). There are 500 features and 50000 examples. 40000 of them are used for training and the rest 10000 are used for testing.

I have spent today trying to trace down why the issue happened. The cause is that bias(or theta in `wT dot x + theta`) is changing along with the weight vector w. If it is a promotion case, `bias *= promotion_rate`. If it is a demotion case, `bias *= demotion_rate`. This bias or theta should be a fixed value.

I can see why the mistake occurred. Normally when we compute `wT dot x`, we add one more dimension to x with value 1 and add one more dimension to w with value of initial theta value, so we can compute the dot product easily. But this bias should stay as a fixed value.

So the fix is to have the bias fixed.

Please correct me if my understanding is incorrect.

@danyaljj @christos-c @danr-ccg Please review this PR.

**Comment by danyaljj** [comment]
Sorry for delay @yimingjiang. Are you sure you are using it right? `LinearThresholdUnit ` which is internally used inside `SparseWinnow` already [contains a bias variable](https://github.com/yimingjiang/lbjava/blob/fix-SparseWinnow/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/LinearThresholdUnit.java#L98-L101).

**Comment by yimingjiang** [comment]
@danyaljj Some other algorithms also inherited from `LinearThresholdUnit`, such as `SparsePerceptron`, `SparseAveragedPerceptron`. There is indeed a `bias` variable in `LinearThresholdUnit`. This is supposed to be there to help with learning.

However, the issue is in `SparseWinnow`, not in `LinearThresholdUnit`. The `bias` should not get updated in `SparseWinnow`. I believe that I have used it correctly.

The question now is should bias get updated with the promotion/demotion rate, or should it stay fixed? I believe the answer is to have the bias fixed. Please correct me if my understanding is incorrect.

@christos-c @mssammon @danr-ccg

**Comment by danyaljj** [comment]
Answer me this: how/when this new `bias` parameter that you have introduced is going to be used in the prediction time?

**Comment by yimingjiang** [comment]
In prediction, if (wT dot x + bias) > 0, predict positive label +1, otherwise, predict negative label -1.

In training, if y(wT dot x + bias) < margin, an mistake is made so make updates on w. The rate for promotion is `learningRate` and the rate for demotion is `1/learningRate`.

**Comment by danyaljj** [comment]
I understand how it works. What I mean is, point me to the code which does what you think: 
> In prediction, if (wT dot x + bias) > 0, predict positive label +1, otherwise, predict negative label -1.

**Comment by yimingjiang** [comment]
Sorry I misunderstood.

Here are the steps:

Firstly, [`classify`](https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/LinearThresholdUnit.java#L599-L602) is called.

It then calls [`featureValue`](https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/LinearThresholdUnit.java#L565-L567).

Where `score` computes `wT dot x + bias` [here](https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/LinearThresholdUnit.java#L626-L629).

`threshold` is default to `defaultThreshold` which is 0.

**Comment by danyaljj** [comment]
And could you elaborate on this (and/or point out to the corresponding code)?:  
> `SparseWinnow` use a constant 1 as bias(theta) and there is no way to set it by the user.

**Comment by yimingjiang** [comment]
As you can see from the constructor in `SparseWinnow` [here](https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/SparseWinnow.java#L242-L252), there is no interface to set bias by the user.

In `LinearThresholdUnit` [here](https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/LinearThresholdUnit.java#L283-L291), bias is set to `initialWeight` which is 1.

It's fine to always set the bias to 1. I was just trying to give more flexibility on `SparseWinnow`. The key issue is that this bias should stay as a constant.

**Comment by danyaljj** [comment]
Honestly what Nick does makes more sense to me. 
I wanna reproduce the issue that you mentioned: 
> When I was using `SparseWinnow`, I ran into the problem that the accuracy is always around 50%. The issue is that `SparseWinnow` use a constant 1 as bias(theta) and there is no way to set it by the user.

Do you remember which example you tried to run?

**Comment by danr-ccg** [comment]
Hi Yiming, Daniel,

Let's set up time to discuss this on Monday. From the correspondence I did not manage to understand why a change is needed and if so, which change. It will also be a good chance to talk about the neural network learner.

Can we meet at 11, say?

Thanks,
  Dan



On Mar 25, 2016, at 9:00 AM, Daniel Khashabi <notifications@github.com<mailto:notifications@github.com>> wrote:


Honestly what Nick does makes more sense to me.
I wanna reproduce the issue that you mentioned:

When I was using SparseWinnow, I ran into the problem that the accuracy is always around 50%. The issue is that SparseWinnow use a constant 1 as bias(theta) and there is no way to set it by the user.

Do you remember which example you tried to run?

**Comment by yimingjiang** [comment]
Upon discussion, the original implementation makes more sense.

**Pull request closed without merging**
