### PR TITLE
Made `setWeight` public

### LINKED ISSUE #84: make the setWeight for SparseNetwork public
I need to use `setWeight` in Saul but this is is not accessible [here] (https://github.com/IllinoisCogComp/lbjava/blob/master/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/SparseWeightVector.java#L94), I tried some work arounds using `scaledAdd` but I see it has introduced some other bugs... . Could someone change this urgently, please?

### PR DESCRIPTION
**Pull request by christos-c**
Closes #84

### CODE REVIEW

**Comment by kordjamshidi** [comment]
Thanks a lot, should I wait for @danyaljj  to merge?

**Comment by christos-c** [comment]
This is a minor change with no adverse effects that I can see. It's fine with me if you just merge, but please remember to run `sh increment-pom-versions.sh`, push to master directly (the updated poms) and `mvn deploy` it. Thanks.

**Comment by kordjamshidi** [comment]
ah, could you please make the version change as well?

**Comment by christos-c** [comment]
done. but I cannot `mvn deploy`, you need to do that (after pulling the latest from the main fork)

**Comment by kordjamshidi** [comment]
@danyaljj could you help with deploying?

**Comment by kordjamshidi** [comment]
@danyaljj, @christos-c , I did deploy to mvn repo, though I still do not see it there. Thanks.

**Comment by christos-c** [comment]
Have you checked the permissions?

**Comment by kordjamshidi** [comment]
yes, it seems the problem is with the permissions.

**Comment by kordjamshidi** [comment]
it would be helpful if someone can make the deploy instead of me.

**Comment by christos-c** [comment]
Version 1.2.24 is now deployed

**Pull request merged**
