### PR TITLE
- add the possibility of using a loss augmented score to the learner

### PR DESCRIPTION
**Pull request by kordjamshidi**

### CODE REVIEW

**Comment by christos-c** [comment]
@kordjamshidi I can't view the diff on github. Why are there "1,469 additions, 1,434 deletions"? Were the changes so massive or did you change the indentation?

**Comment by kordjamshidi** [comment]
Ah, I see, the reason is that my fork had been isolated from this repo and I needed to fork again and copied the whole file that I had changed from my old fork to the new one. But actually I could see diff I think.

**Comment by christos-c** [comment]
I'm not sure what that implies. Are you going to resubmit? I cannot merge what I cannot see.

**Comment by kordjamshidi** [comment]
I don't know, the difference is like when you do reformatting, it is only in spacing, I am not  sure why it does not show it.

**Comment by christos-c** [comment]
It doesn't show it because it's too many changes. So I would suggest you undo the formatting changes and push again.

**Comment by danyaljj** [comment]
It's because the style change; for your convenience I created this diff based on Paris's change:
https://www.diffnow.com/?report=4nbwd

PS. We should add [auto-formatter to lbjava as well](https://github.com/cogcomp-dev/illinois-cogcomp-nlp/pull/86), otherwise we will have more of these issues in future.

**Comment by kordjamshidi** [comment]
Thanks @danyaljj, for the diff. I can push again now.  About the method, it is basically to update the score of each binary variable (label) based on the gold value of each example for that variable. If the gold is same as a specific label then its value is 1 and the offset will be `oldscore - lossOffset` and otherwise it will be `oldscore+lossoffset`. It is like this if you do some simple algebraic operations to simplify the objective that include a hmming loss for each label, you can see the type of objective of the loss-augmented inference in my PhD thesis here, page 173:    
https://www.researchgate.net/publication/269519103_Structured_Machine_Learning_for_Mapping_Natural_Language_to_Spatial_Ontologies

**Comment by danyaljj** [comment]
@kordjamshidi could you update this with upstream/master?

**Comment by kordjamshidi** [comment]
Do you want to merge it?

**Comment by danyaljj** [comment]
potentially, yes.

**Comment by kordjamshidi** [comment]
I have had difficulties to upgrade, there are too many edits in upstream and conflicts.

**Comment by kordjamshidi** [comment]
Yes, indeed there should be some priorities according to the timing of the PRs as well as the amount of changes. When I issued my PR everything was up to date but it was not merged until the upstream had a lot of modifications.

**Comment by christos-c** [comment]
Replaced by #75

**Pull request closed without merging**
