### PR TITLE
Adding the autoformatter plugin 

### PR DESCRIPTION
**Pull request by danyaljj**
Same as: https://github.com/cogcomp-dev/illinois-cogcomp-nlp/pull/86 
No change of functionality.

### CODE REVIEW

**Comment by christos-c** [comment]
@danyaljj make sure the autogenerated files (`sym` and `parser`) get the same treatment for their license.

**Comment by danyaljj** [comment]
ugh I explicitly ignored them in the plugin settings; this would create extra complication in the future ...

**Comment by christos-c** [comment]
It's up to you. I feel like it would be nice for those two to get the license unless we plan to update the text/style again.

**Comment by danyaljj** [comment]
oooops I thought you're talking about *formatting* ... 
So about *license* stuff; I updated `scanner.jlx` according to #34 .

**Comment by christos-c** [comment]
oh great! let me know when you're ready and I can merge

**Comment by danyaljj** [comment]
I already did it.

**Comment by christos-c** [comment]
but it still says WIP :stuck_out_tongue:

**Comment by danyaljj** [comment]
Done.

**Pull request merged**
